CREATE TABLE Pago (
IdPago INT IDENTITY (1,1) NOT NULL,
Concepto TINYINT NOT NULL,
Fecha DATETIME NOT NULL,
Monto MONEY NOT NULL,
Estado TINYINT NOT NULL,
Observacion VARCHAR(1000),
CONSTRAINT PK_Pago PRIMARY KEY (IdPago)
)